### ISSUE TITLE
Expand globstar

### ISSUE THREAD

**Issue by karrybit** [k2tzumi/runn-action#44]
Thank you for your consistent maintenance efforts.

In our project, we organize the definition of runbooks under the runn directory. Within the runn directory, subdirectories are structured hierarchically based on their context, such as `apis` or `jobs`. When running runn in GHA, we specify `path_pattern` as `runn/**/*.yaml` to test them collectively. However, this path pattern does not execute the runbooks recursively.

Your Action uses bash, but bash does not automatically expand globstar patterns. As a result, it failed to recognize the runbooks recursively.

Organizing runbooks in meaningful directory hierarchies is a common use case. To support this use case, I would like you to enable support for globster expansion.

As a workaround, it is possible to pass `"$(find runn -type f -name '*.yaml')"` to recognize all runbooks.

**Comment by k2tzumi** [comment]
#45 merged.
